# Generated by Django 4.2.1 on 2023-11-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphic',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='web',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='image',
            field=models.ImageField(upload_to='images/graphic'),
        ),
        migrations.AlterField(
            model_name='web',
            name='image',
            field=models.ImageField(upload_to='images/web'),
        ),
    ]
