# Generated by Django 4.2.1 on 2023-11-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_graphic_slug_alter_web_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='graphic',
            options={'verbose_name': 'GRAPHIC works', 'verbose_name_plural': 'GRAPHIC works'},
        ),
        migrations.AlterModelOptions(
            name='web',
            options={'verbose_name': 'WEB works', 'verbose_name_plural': 'WEB works'},
        ),
    ]
