# Generated by Django 4.2.1 on 2023-11-07 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_mail_alter_graphic_options_alter_web_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cv',
            options={'verbose_name': 'CV', 'verbose_name_plural': 'CV'},
        ),
        migrations.AlterModelOptions(
            name='mail',
            options={'verbose_name': 'Mail', 'verbose_name_plural': 'Mail'},
        ),
        migrations.AddField(
            model_name='graphic',
            name='big_image',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='images/graphic/big'),
        ),
        migrations.AddField(
            model_name='web',
            name='big_image',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='images/web/big'),
        ),
    ]
